### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alxmamaev**
Parse function requirement generator on input, not a string.

### CODE REVIEW

**Comment by unhammer** [comment]
Thanks, although  … should this be considered a bug in `parse`? @sushain97 it feels a little unexpected that parse doesn't take a string. Or maybe we just need a simple wrapper like parse_string?

**Comment by sushain97** [comment]
> Thanks, although … should this be considered a bug in parse? @sushain97 it feels a little unexpected that parse doesn't take a string. 

I was about to say exactly this.

> Or maybe we just need a simple wrapper like parse_string?

I think just detecting the type and proceeding accordingly is fine.

**Comment by sushain97** [comment]
Oh, this matches up with #8.

**Comment by sushain97** [comment]
Solved at some point in my recent renovation of this lib.

**Pull request closed without merging**
