### PR TITLE
initial packaging info

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I'm not sure about adding t/* stuff to the MANIFEST.in file. Should we? The tests look a bit vague at the moment, maybe that case could be also improved.

**Comment by ghost** [comment]
Ok. I read https://docs.python.org/3.4/distutils/sourcedist.html#specifying-the-files-to-distribute and basically from that I understood that we should get all (but not travis, .gitignore, etc. stuff) the source code files. So it means that t/* should be included, too. I will amend to the previous commit that added README.md and LICENSE.

**Comment by ghost** [comment]
@unhammer, @sushain97: looks good? Btw, I now later noticed Frankie's pull request on the same topic, I wonder why that was closed back then.

**Comment by unhammer** [comment]
#6 ? I have no idea! Maybe I hit the wrong button? I'll try to do better this time

**Pull request merged**
